

schools:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8070,http://localhost:8071, http://localhost:8072
 
server:
  port: 9090

spring:
  main:
    allow-circular-references: true